title: Standard Adresse
description: L'objectif de ce document est la définition des concepts d'adresses et des composantes d'adressage en France, en cohérence avec les spécifications Adresse de la directive INSPIRE et la norme internationale ISO 19160 concernant l'adressage. Il fournit les définitions des concepts adresses et des composantes d'adressage, cela comprend : le périmètre BAN actuellement défini sur la compétence communale, et les composantes adresses nécessaires à une utilisation d'adresses plus détaillées (ex : bâtiments sur site privé ou intérieur des bâtiments notamment).
homepage: https://cnig.gouv.fr/ressources-adresse-a26286.html
version: 1.0
lastModified: 2024-10-24
